<?php include "header.php"; ?>
<?php
if (!isset($_SESSION['username'])) {
    header('location:signup.php');
}
?>

<?php
// payment with rozarpay

$apikey = "rzp_test_ND6O9kA1rtn8eX";

?>

<form action="contribution.php" method="POST">
    <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys data-amount="<?php echo $_POST['amount'] * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35. data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account data-id="<?php echo 'OID' . rand(10, 100) . 'END'; ?>"//Replace with the order_id generated by you in the backend. data-buttontext="Pay with Razorpay" data-name="Covid-19 Awareness" data-description="Help for whom who fighting with corona virus" data-image="" data-prefill.name="<?php echo $_POST['name']; ?>" data-prefill.email="<?php echo $_POST['email']; ?>" data-theme.color="#9F44D3"></script><input type="hidden" custom="Hidden Element" name="hidden">
</form>

<script>
    window.onload = function(){
    var button = document.getElementsByClassName('razorpay-payment-button').value;
    button.form.submit();
}
</script>


<?php
if (isset($_POST['save'])) {

    $name = $_POST['name'];
    $email = $_POST['email'];
    $mobile = $_POST['mobile'];
    $amount = $_POST['amount'];
    $reason = $_POST['reason'];

    // Real Escape String
    $name = mysqli_real_escape_string($conn, $name);
    $email = mysqli_real_escape_string($conn, $email);
    $mobile = mysqli_real_escape_string($conn, $mobile);
    $amount = mysqli_real_escape_string($conn, $amount);
    $reason = mysqli_real_escape_string($conn, $reason);

    if ($name == '' || $email == '' || $amount == '' || $reason == '') {
        echo "Please Enter All Data!";
    } else {

        $query = "INSERT INTO `contra` (`contra_id`, `name`, `email`, `mobile`, `amount`, `reason`) VALUES (NULL, '$name', '$email', '$mobile','$amount', '$reason');";
        $result = mysqli_query($conn, $query);
        if ($result) {
            header('location:contribution.php');
        } else {
            echo mysqli_error($conn);
        }
    }
}

?>


<div class="container-fluid text-center my-5">
    <div class="row">
        <!-- <div class="col-md-6">
            <img class="img-fluid" id="" src="./images/svg/contact.svg" alt="Contact me">
        </div> -->

        <div class="col-lg-6">
            <img class="img-fluid" id="" src="./images/contribution.jpg" alt="Contact me">
        </div>
        
        <div class="col-lg-6">
            <form class="needs-validation" novalidate method="post" action="contribution.php">
                <div class="form-group">
                    <div class="col-md-12 mb-3">
                        <label for="validationCustom01">Full Name</label>
                        <input type="text" name="name" class="form-control" id="validationCustom01" required>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" required>
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="validationCustom01">Mobile</label>
                        <input type="text" name="mobile" class="form-control" id="validationCustom01" required>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="amount">Amount</label>
                        <input type="number" class="form-control" name="amount" id="amount" aria-describedby="emailHelp" required>
                    </div>
                    <div class="col-md-12 mb-3">
                        <div class="form-group green-border-focus">
                            <label for="exampleFormControlTextarea5">Project Details</label>
                            <textarea class="form-control" id="exampleFormControlTextarea5" name="reason" rows="3" required></textarea>
                        </div>
                    </div>
                    <!-- </div>
                <div class="form-group"> -->
                    <div class="form-check custom-control custom-checkbox form-check">
                        <input class="form-check-input custom-control-input" type="checkbox" id="invalidCheck" required>
                        <label class="custom-control-label" for="invalidCheck">
                            Agree to terms and conditions
                        </label>
                    </div>
                    <div class="invalid-feedback">
                        You must agree before submitting.
                    </div>
                </div>
                <button class="btn btn-success" name="save" type="submit">Pay Now</button>
            </form>
        </div>
    </div>
</div>
<!-- </div> -->

<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>


</div>

<?php include './footer.php'; ?>